services:
  - type: web
    name: muratech-backend
    runtime: java
    plan: free
    rootDir: backend-spring-boot
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar

  - type: web
    name: muratech-frontend
    runtime: static
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build
    staticPublishPath: dist
